package com.exception;
/*
 * finally : whether there is a error in the code or not finally block will definitely run after the
 * last catch or try
 * it is used in the important code when the connection need to close or file need to close 
 */
public class ExceptionFinally {
public static void main(String[] args) {
	int []a=new int[5];
	try {
		for (int i = 0; i <5; i++) {
			a[i]=i;
			System.out.println(a[i]);
		}
	} catch (Exception e) {
		// TODO: handle exception
		e.printStackTrace();
	}
	finally {
		System.out.println("code is generated by Adarsh");
		System.out.println("Mobile number : 9962146456");
	}
}
}
